version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: scripts/before_install.ps1
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.ps1
      timeout: 300
